version: '3.6'

services:
    mongo:
        image: mongo:latest
        ports:
            - 27017:27017
        restart: always
        container_name: mongodb
        volumes:
            - /mnt/c/Git-Projects/csci_e59/final/data/db:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
        networks:
            - backend

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
            ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo:27017/
        depends_on:
            - mongo
        networks:
            - backend

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
